In [122]:
import pandas as pd
import numpy as np

# Introduction
In this notebook we will treat the go_emotions dataset from google research to fit in our model. Our objective here is to reduce the dataset from the original size to give us only the information we need, in this case the column ['text'] and ['emotion']

##

## First step:

We load up the data and drop the columns we don't need

In [123]:
go_emotions_1 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_1.csv')
go_emotions_2 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_2.csv')
go_emotions_3 = pd.read_csv('https://storage.googleapis.com/gresearch/goemotions/data/full_dataset/goemotions_3.csv')
go_emotions = pd.concat([go_emotions_1, go_emotions_2, go_emotions_3])

In [124]:
go_emotions.loc[go_emotions['example_very_unclear']==True] = np.nan
go_emotions.dropna(inplace=True)
go_emotions.drop(['id', 'author', 'subreddit', 'link_id', 'parent_id',
                  'created_utc', 'rater_id', 'example_very_unclear'], axis =1, inplace=True)
go_emotions

C:\Users\adamc\AppData\Local\Temp\ipykernel_13228\2176924920.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  go_emotions.loc[go_emotions['example_very_unclear']==True] = np.nan

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,"You do right, if you don't care then fuck 'em!",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Man I love reddit.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,"[NAME] was nowhere near them, he was by the Fa...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,Right? Considering it’s such an important docu...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71219,"Well, I'm glad you're out of all that now. How...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71220,Everyone likes [NAME].,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71221,Well when you’ve imported about a gazillion of...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71222,That looks amazing,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71223,The FDA has plenty to criticize. But like here...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Second Step:
As u can see before emotions are treated as a numerical form in a ton of columns, our goal is to have all the information only in two columns, [text] containing the message and [emotion] containing the emotion

In [125]:

df = go_emotions.copy()

In [126]:

text_col = "text"

emotion_cols = go_emotions.columns.drop('text')

In [127]:
for col in emotion_cols:
    df[col] = df[col].replace({1: col, 0: np.nan})

df

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sadness,NaN,NaN
2,"You do right, if you don't care then fuck 'em!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
3,Man I love reddit.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[NAME] was nowhere near them, he was by the Fa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
5,Right? Considering it’s such an important docu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71219,"Well, I'm glad you're out of all that now. How...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71220,Everyone likes [NAME].,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71221,Well when you’ve imported about a gazillion of...,NaN,NaN,NaN,NaN,NaN,caring,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71222,That looks amazing,admiration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71223,The FDA has plenty to criticize. But like here...,NaN,NaN,anger,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
emotion_cols

Index(['admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring',
       'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval',
       'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief',
       'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization',
       'relief', 'remorse', 'sadness', 'surprise', 'neutral'],
      dtype='object')

we ajust the emotions to the 5 we'll use in the final model and drop the rest

In [129]:
df.replace(['admiration', 'amusement','excitement', 'love', 'optimism'], 'joy', inplace=True)
df.replace(['grief', 'sadness'], 'sad', inplace=True)
df.replace(['embarrassment', 'nervousness'], 'fear', inplace=True)
df.replace(['annoyance', 'disappointment', 'disgust'], 'anger', inplace=True)
not_useful = ['approval', 'caring', 'confusion', 'curiosity', 'desire', 'disapproval', 
              'gratitude', 'pride', 'realization',  'relief', 'remorse', 'neutral']
df.drop(columns=not_useful, inplace=True)

In [130]:
df['joy'].fillna(df['admiration'], inplace=True)
df['joy'].fillna(df['amusement'], inplace=True)
df['joy'].fillna(df['excitement'], inplace=True)
df['joy'].fillna(df['love'], inplace=True)
df['joy'].fillna(df['optimism'], inplace=True)
df['sadness'].fillna(df['grief'], inplace=True)
df['fear'].fillna(df['embarrassment'], inplace=True)
df['fear'].fillna(df['nervousness'], inplace=True)
df['anger'].fillna(df['annoyance'], inplace=True)
df['anger'].fillna(df['disappointment'], inplace=True)
df['anger'].fillna(df['disgust'], inplace=True)

C:\Users\adamc\AppData\Local\Temp\ipykernel_13228\3029742281.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['joy'].fillna(df['admiration'], inplace=True)
C:\Users\adamc\AppData\Local\Temp\ipykernel_13228\3029742281.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sadness'].fillna(df['grief'], inplace=True)
C:\Users\adamc\AppData\Local\Temp\ipykernel_13228\3029742281.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fear'].fillna(df['embarrassment'], inplace=True)
C:\Users\adamc\AppData\Local\Temp\ipykernel_13228\3029742281.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['anger'].fillna(df['annoyance'], inplace=True)

In [131]:
final_emotions = ['joy', 'sadness', 'anger', 'fear', 'surprise']

In [132]:
foo = emotion_cols.drop(final_emotions)
foo = foo.drop(not_useful)
foo

Index(['admiration', 'amusement', 'annoyance', 'disappointment', 'disgust',
       'embarrassment', 'excitement', 'grief', 'love', 'nervousness',
       'optimism'],
      dtype='object')

In [133]:
df.drop(foo, axis=1, inplace=True)
df.replace(np.nan, '', inplace=True)
df

,text,anger,fear,joy,sadness,surprise
0,That game hurt.,,,,sad,
2,"You do right, if you don't care then fuck 'em!",,,,,
3,Man I love reddit.,,,joy,,
4,"[NAME] was nowhere near them, he was by the Fa...",,,,,
5,Right? Considering it’s such an important docu...,,,,,
...,...,...,...,...,...,...
71219,"Well, I'm glad you're out of all that now. How...",,,joy,,
71220,Everyone likes [NAME].,,,joy,,
71221,Well when you’ve imported about a gazillion of...,,,,,
71222,That looks amazing,,,joy,,
71223,The FDA has plenty to criticize. But like here...,anger,,,,

In the cell below we are doing so text that only have 1 emotion saves as so and texts that have more than 1 emotion saves as a python list

In [ ]:
df["emociones_merged"] = df[final_emotions].apply(
    lambda fila: [val for val in fila if val != ''][0] if sum(fila != '') == 1 
                 else [val for val in fila if val != ""], 
    axis=1
)

In [135]:
df.drop(final_emotions, axis=1, inplace=True)

In [136]:
df

                                                    text emociones_merged
0                                        That game hurt.              sad
2         You do right, if you don't care then fuck 'em!               []
3                                     Man I love reddit.              joy
4      [NAME] was nowhere near them, he was by the Fa...               []
5      Right? Considering it’s such an important docu...               []
...                                                  ...              ...
71219  Well, I'm glad you're out of all that now. How...              joy
71220                             Everyone likes [NAME].              joy
71221  Well when you’ve imported about a gazillion of...               []
71222                                 That looks amazing              joy
71223  The FDA has plenty to criticize. But like here...            anger

[207814 rows x 2 columns]

In [ ]:
void = df.iloc[1][1]
df.replace(void, np.nan, inplace=True)
df.dropna(inplace=True)
df

C:\Users\adamc\AppData\Local\Temp\ipykernel_13228\3304048317.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  void = df.iloc[1][1]

                                                    text emociones_merged
0                                        That game hurt.              sad
2         You do right, if you don't care then fuck 'em!               []
3                                     Man I love reddit.              joy
4      [NAME] was nowhere near them, he was by the Fa...               []
5      Right? Considering it’s such an important docu...               []
...                                                  ...              ...
71219  Well, I'm glad you're out of all that now. How...              joy
71220                             Everyone likes [NAME].              joy
71221  Well when you’ve imported about a gazillion of...               []
71222                                 That looks amazing              joy
71223  The FDA has plenty to criticize. But like here...            anger

[207814 rows x 2 columns]

                                                    text emociones_merged
0                                        That game hurt.              sad
2         You do right, if you don't care then fuck 'em!               []
3                                     Man I love reddit.              joy
4      [NAME] was nowhere near them, he was by the Fa...               []
5      Right? Considering it’s such an important docu...               []
...                                                  ...              ...
71219  Well, I'm glad you're out of all that now. How...              joy
71220                             Everyone likes [NAME].              joy
71221  Well when you’ve imported about a gazillion of...               []
71222                                 That looks amazing              joy
71223  The FDA has plenty to criticize. But like here...            anger

[207814 rows x 2 columns]

## Final Step
We save the treated dataset in .csv

In [137]:
df.to_csv("goemotions_full_clean.csv", index=False)