# SemEval E Treatment

>Here we will treat and process the dataframe semeval-e wich is a subset from SemEval 2018 to work with it with the others dataframes and to make it fit to our model. We will simplyfy it as we did with the others in data-collection.ipynb, leaving it with only two columns, one with the text and the other with the emotion.

In [1]:
import pandas as pd
import numpy as np

## Basic simplification
>We will start importing the dataframe and doing as we did with the other dataframes, erasing columns that are useless for this project and a simple general data treatment. And as we did with the other dataframes we will show the top 5 elements.

In [2]:
semeval_e = pd.read_csv('../data/raw/semeval-e.csv')

In [3]:
semeval_e.drop(columns=['ID'], inplace=True)
semeval_e.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1
1,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0
2,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0
3,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0
4,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0

>As we can see, we do not have a column for emotions; instead, we have a column for each emotion, where each one contains zeros or ones to indicate whether the emotion is present or not. The next step is to solve this.

## Solving the emotions column problem

>To start solving the problem we change the zeros for NaN and the ones for the emotion shown in each column.

In [4]:
emotion_cols = semeval_e.columns.drop('Tweet')

for col in emotion_cols:
    semeval_e[col] = semeval_e[col].replace({1: col, 0: np.nan})

semeval_e.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,NaN,anticipation,NaN,NaN,NaN,NaN,optimism,NaN,NaN,NaN,trust
1,Whatever you decide to do make sure it makes y...,NaN,NaN,NaN,NaN,joy,love,optimism,NaN,NaN,NaN,NaN
2,@Max_Kellerman it also helps that the majorit...,anger,NaN,disgust,NaN,joy,NaN,optimism,NaN,NaN,NaN,NaN
3,Accept the challenges so that you can literall...,NaN,NaN,NaN,NaN,joy,NaN,optimism,NaN,NaN,NaN,NaN
4,My roommate: it's okay that we can't spell bec...,anger,NaN,disgust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

>The second step will be to delete the emotions that we are not going to use for our model and merge some emotions into one that can contain them.

In [5]:
semeval_e.columns

Index(['Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love',
       'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
      dtype='object')

In [6]:
semeval_e.replace(['sadness', 'pessimism'], 'sad', inplace=True)
semeval_e.replace(['love', 'optimism'], 'joy', inplace=True)
semeval_e.replace(['disgust'], 'anger', inplace=True)

semeval_e.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,NaN,anticipation,NaN,NaN,NaN,NaN,joy,NaN,NaN,NaN,trust
1,Whatever you decide to do make sure it makes y...,NaN,NaN,NaN,NaN,joy,joy,joy,NaN,NaN,NaN,NaN
2,@Max_Kellerman it also helps that the majorit...,anger,NaN,anger,NaN,joy,NaN,joy,NaN,NaN,NaN,NaN
3,Accept the challenges so that you can literall...,NaN,NaN,NaN,NaN,joy,NaN,joy,NaN,NaN,NaN,NaN
4,My roommate: it's okay that we can't spell bec...,anger,NaN,anger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

>After changing the name of the emotions we have to merge the data from the columns in the only five we will use in our model and delete the rest of the columns.

In [7]:
semeval_e['joy'].fillna(semeval_e['love'], inplace=True)
semeval_e['joy'].fillna(semeval_e['optimism'], inplace=True)
semeval_e['sadness'].fillna(semeval_e['pessimism'], inplace=True)
semeval_e['anger'].fillna(semeval_e['disgust'], inplace=True)
semeval_e.drop(['anticipation', 'trust', 'love', 'optimism', 'pessimism', 'disgust'], axis=1, inplace=True)
semeval_e.head()

C:\Users\adamc\AppData\Local\Temp\ipykernel_8120\3772326632.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  semeval_e['joy'].fillna(semeval_e['love'], inplace=True)
C:\Users\adamc\AppData\Local\Temp\ipykernel_8120\3772326632.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  semeval_e['sadness'].fillna(semeval_e['pessimism'], inplace=True)
C:\Users\adamc\AppData\Local\Temp\ipykernel_8120\3772326632.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  semeval_e['anger'].fillna(semeval_e['disgust'], inplace=True)

,Tweet,anger,fear,joy,sadness,surprise
0,“Worry is a down payment on a problem you may ...,NaN,NaN,joy,NaN,NaN
1,Whatever you decide to do make sure it makes y...,NaN,NaN,joy,NaN,NaN
2,@Max_Kellerman it also helps that the majorit...,anger,NaN,joy,NaN,NaN
3,Accept the challenges so that you can literall...,NaN,NaN,joy,NaN,NaN
4,My roommate: it's okay that we can't spell bec...,anger,NaN,NaN,NaN,NaN

>To make the dataframe cleaner and as we don't need more the NaN, we will change them into blank spaces.

In [8]:
semeval_e.replace(np.nan, '', inplace=True)
semeval_e.head()

,Tweet,anger,fear,joy,sadness,surprise
0,“Worry is a down payment on a problem you may ...,,,joy,,
1,Whatever you decide to do make sure it makes y...,,,joy,,
2,@Max_Kellerman it also helps that the majorit...,anger,,joy,,
3,Accept the challenges so that you can literall...,,,joy,,
4,My roommate: it's okay that we can't spell bec...,anger,,,,

>And now its time to merge it to just one column

In [9]:
final_emotions = semeval_e.columns.drop('Tweet')

semeval_e["emotions_merged"] = semeval_e[final_emotions].apply(
    lambda fila: [val for val in fila if val != ''][0] if sum(fila != '') == 1 
                 else [val for val in fila if val != ""], 
    axis=1
)

semeval_e.drop(final_emotions, axis=1, inplace=True)
semeval_e.head()

                                               Tweet emotions_merged
0  “Worry is a down payment on a problem you may ...             joy
1  Whatever you decide to do make sure it makes y...             joy
2  @Max_Kellerman  it also helps that the majorit...    [anger, joy]
3  Accept the challenges so that you can literall...             joy
4  My roommate: it's okay that we can't spell bec...           anger

>As you can see, there is data without any emotions of the ones we are working on and there is also data with multiple basic emotions which means that it is confusing data, so we are deleting all of it using a function to see if it's a list or just a emotion to finish the treatment of the dataset.

In [10]:
def clean_lists(val):
    if isinstance(val, list):
        return np.nan
    else:
        return val

for col in semeval_e.columns:
    semeval_e[col] = semeval_e[col].apply(clean_lists)

semeval_e.dropna(inplace=True)
semeval_e.head()

                                               Tweet emotions_merged
0  “Worry is a down payment on a problem you may ...             joy
1  Whatever you decide to do make sure it makes y...             joy
3  Accept the challenges so that you can literall...             joy
4  My roommate: it's okay that we can't spell bec...           anger
5  No but that's so cute. Atsu was probably shy a...             joy

## Data Save
>We are finally saving the dataset treated to the subfolder preprocessed of data.

In [11]:
semeval_e.to_csv("../data/preprocessed/semeval_e.csv", index=False)