In [3]:
import pandas as pd
import numpy as np

In [2]:
semeval_e_train = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-train.txt', sep='\t')
semeval_e_test = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-test-gold.txt', sep='\t')
semeval_e_dev = pd.read_csv('../data/raw/English/E-c/2018-E-c-En-dev.txt', sep='\t')
semeval_e = pd.concat([semeval_e_train, semeval_e_test, semeval_e_dev])

### verificamos si hay columnas que no nos interesa

In [5]:
semeval_e.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2017-En-21441,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1
1,2017-En-31535,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0
2,2017-En-21068,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0
3,2017-En-31436,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0
4,2017-En-22195,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0

In [9]:
semeval_e.drop(columns=['ID'], inplace=True)

In [10]:
semeval_e.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1
1,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0
2,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0
3,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0
4,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0

In [11]:
df= semeval_e.copy()

In [13]:
emotion_cols = semeval_e.columns.drop('Tweet')

#### con esto reemplazamos los 1 por las emociones y los 0 desaparecen

In [ ]:

for col in emotion_cols:
    df[col] = df[col].replace({1: col, 0: ""})

df

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,,anticipation,,,,,optimism,,,,trust
1,Whatever you decide to do make sure it makes y...,,,,,joy,love,optimism,,,,
2,@Max_Kellerman it also helps that the majorit...,anger,,disgust,,joy,,optimism,,,,
3,Accept the challenges so that you can literall...,,,,,joy,,optimism,,,,
4,My roommate: it's okay that we can't spell bec...,anger,,disgust,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
881,@BadHombreNPS @SecretaryPerry If this didn't m...,anger,,disgust,,,,,,,,
882,Excited to watch #stateoforigin tonight! Come ...,,,,,joy,,optimism,,,,
883,"Blah blah blah Kyrie, IT, etc. @CJC9BOSS leavi...",anger,,disgust,,,,,,sadness,,
884,#ThingsIveLearned The wise #shepherd never tru...,,,,,,,,,,,
885,I am really flattered and happy to hear those ...,,,,,joy,,optimism,,,,

In [15]:
df["emociones_merged"] = df[emotion_cols].apply(
    lambda fila: [val for val in fila if val != ""][0] if sum(fila != "") == 1 
                 else [val for val in fila if val != ""],
    axis=1
)
df.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust,emociones_merged
0,“Worry is a down payment on a problem you may ...,,anticipation,,,,,optimism,,,,trust,"[anticipation, optimism, trust]"
1,Whatever you decide to do make sure it makes y...,,,,,joy,love,optimism,,,,,"[joy, love, optimism]"
2,@Max_Kellerman it also helps that the majorit...,anger,,disgust,,joy,,optimism,,,,,"[anger, disgust, joy, optimism]"
3,Accept the challenges so that you can literall...,,,,,joy,,optimism,,,,,"[joy, optimism]"
4,My roommate: it's okay that we can't spell bec...,anger,,disgust,,,,,,,,,"[anger, disgust]"

### Aqui eliminamos las columnas sobrantes.

In [16]:
df.drop(columns=emotion_cols, inplace=True)

In [17]:
df.head()

,Tweet,emociones_merged
0,“Worry is a down payment on a problem you may ...,"[anticipation, optimism, trust]"
1,Whatever you decide to do make sure it makes y...,"[joy, love, optimism]"
2,@Max_Kellerman it also helps that the majorit...,"[anger, disgust, joy, optimism]"
3,Accept the challenges so that you can literall...,"[joy, optimism]"
4,My roommate: it's okay that we can't spell bec...,"[anger, disgust]"

In [18]:
df.to_csv('../data/preprocessed/semeval-e.csv', index=False)