# SemEval E Treatment

>Here we will treat and process the dataframe semeval-e wich is a subset from SemEval 2018 to work with it with the others dataframes and to make it fit to our model. We will simplyfy it as we did with the others in data-collection.ipynb, leaving it with only two columns, one with the text and the other with the emotion.

In this notebook we will treat the semeval-e dataset from SemEval research to fit in our model. Our objective here is to reduce the dataset from the original size to give us only the information we need, in this case the column ['Tweet'] and ['emotions_merged']

In [1]:
import pandas as pd
import numpy as np

## Basic simplification
>We will start importing the dataframe and doing as we did with the other dataframes, erasing columns that are useless for this project and a simple general data treatment. And as we did with the other dataframes we will show the top 5 elements.

In [3]:
semeval_e = pd.read_csv('../data/raw/semeval-e.csv')

In [4]:
semeval_e.drop(columns=['ID'], inplace=True)
semeval_e.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,0,1,0,0,0,0,1,0,0,0,1
1,Whatever you decide to do make sure it makes y...,0,0,0,0,1,1,1,0,0,0,0
2,@Max_Kellerman it also helps that the majorit...,1,0,1,0,1,0,1,0,0,0,0
3,Accept the challenges so that you can literall...,0,0,0,0,1,0,1,0,0,0,0
4,My roommate: it's okay that we can't spell bec...,1,0,1,0,0,0,0,0,0,0,0

>As we can see, we do not have a column for emotions; instead, we have a column for each emotion, where each one contains zeros or ones to indicate whether the emotion is present or not. The next step is to solve this.

## Solving the emotions column problem

>To start solving the problem we change the zeros for NaN and the ones for the emotion shown in each column.

In [5]:
emotion_cols = go_emotions.columns.drop('text')

for col in emotion_cols:
    go_emotions[col] = go_emotions[col].replace({1: col, 0: np.nan})

go_emotions.head()

,text,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,...,love,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral
0,That game hurt.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sadness,NaN,NaN
2,"You do right, if you don't care then fuck 'em!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
3,Man I love reddit.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,love,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[NAME] was nowhere near them, he was by the Fa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,neutral
5,Right? Considering it’s such an important docu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

>The second step will be to delete the emotions that we are not going to use for our model and merge some emotions into one that can contain them.

In [6]:
go_emotions.replace(['admiration', 'amusement','excitement', 'love', 'optimism'], 'joy', inplace=True)
go_emotions.replace(['grief', 'sadness'], 'sad', inplace=True)
go_emotions.replace(['embarrassment', 'nervousness'], 'fear', inplace=True)
go_emotions.replace(['annoyance', 'disappointment', 'disgust'], 'anger', inplace=True)
not_useful = ['approval', 'caring', 'confusion', 'curiosity', 'desire', 'disapproval', 
              'gratitude', 'pride', 'realization',  'relief', 'remorse', 'neutral']
go_emotions.drop(columns=not_useful, inplace=True)

go_emotions.head()

,text,admiration,amusement,anger,annoyance,disappointment,disgust,embarrassment,excitement,fear,grief,joy,love,nervousness,optimism,sadness,surprise
0,That game hurt.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sad,NaN
2,"You do right, if you don't care then fuck 'em!",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Man I love reddit.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,joy,NaN,NaN,NaN,NaN
4,"[NAME] was nowhere near them, he was by the Fa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Right? Considering it’s such an important docu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

>After changing the name of the emotions we have to merge the data from the columns in the only five we will use in our model and delete the rest of the columns.

In [7]:
go_emotions['joy'].fillna(go_emotions['admiration'], inplace=True)
go_emotions['joy'].fillna(go_emotions['amusement'], inplace=True)
go_emotions['joy'].fillna(go_emotions['excitement'], inplace=True)
go_emotions['joy'].fillna(go_emotions['love'], inplace=True)
go_emotions['joy'].fillna(go_emotions['optimism'], inplace=True)
go_emotions['sadness'].fillna(go_emotions['grief'], inplace=True)
go_emotions['fear'].fillna(go_emotions['embarrassment'], inplace=True)
go_emotions['fear'].fillna(go_emotions['nervousness'], inplace=True)
go_emotions['anger'].fillna(go_emotions['annoyance'], inplace=True)
go_emotions['anger'].fillna(go_emotions['disappointment'], inplace=True)
go_emotions['anger'].fillna(go_emotions['disgust'], inplace=True)
go_emotions.drop(columns=['admiration', 'amusement', 'annoyance', 'disappointment', 'disgust',
       'embarrassment', 'excitement', 'grief', 'love', 'nervousness', 'optimism'],
       inplace=True)
go_emotions.head()

/tmp/ipykernel_2993/2880504146.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  go_emotions['joy'].fillna(go_emotions['admiration'], inplace=True)
/tmp/ipykernel_2993/2880504146.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  go_emotions['sadness'].fillna(go_emotions['grief'], inplace=True)
/tmp/ipykernel_2993/2880504146.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  go_emotions['fear'].fillna(go_emotions['embarrassment'], inplace=True)
/tmp/ipykernel_2993/2880504146.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  go_emotions['anger'].fillna(go_emotions['annoyance'], inplace=True)

,text,anger,fear,joy,sadness,surprise
0,That game hurt.,NaN,NaN,NaN,sad,NaN
2,"You do right, if you don't care then fuck 'em!",NaN,NaN,NaN,NaN,NaN
3,Man I love reddit.,NaN,NaN,joy,NaN,NaN
4,"[NAME] was nowhere near them, he was by the Fa...",NaN,NaN,NaN,NaN,NaN
5,Right? Considering it’s such an important docu...,NaN,NaN,NaN,NaN,NaN

>To make the dataframe cleaner and as we don't need more the NaN, we will change them into blank spaces.

In [8]:
go_emotions.replace(np.nan, '', inplace=True)
go_emotions.head()

,text,anger,fear,joy,sadness,surprise
0,That game hurt.,,,,sad,
2,"You do right, if you don't care then fuck 'em!",,,,,
3,Man I love reddit.,,,joy,,
4,"[NAME] was nowhere near them, he was by the Fa...",,,,,
5,Right? Considering it’s such an important docu...,,,,,

>And now its time to merge it to just one column

In [9]:
final_emotions = go_emotions.columns.drop('text')

go_emotions["emotions_merged"] = go_emotions[final_emotions].apply(
    lambda fila: [val for val in fila if val != ''][0] if sum(fila != '') == 1 
                 else [val for val in fila if val != ""], 
    axis=1
)

go_emotions.drop(final_emotions, axis=1, inplace=True)
go_emotions.head()

                                                text emotions_merged
0                                    That game hurt.             sad
2     You do right, if you don't care then fuck 'em!              []
3                                 Man I love reddit.             joy
4  [NAME] was nowhere near them, he was by the Fa...              []
5  Right? Considering it’s such an important docu...              []

>As you can see, there is data without any emotions of the ones we are working on and there is also data with multiple basic emotions which means that it is confusing data, so we are deleting all of it using a function to see if it's a list or just a emotion to finish the treatment of the dataset.

In [10]:
def clean_lists(val):
    if isinstance(val, list):
        return np.nan
    else:
        return val

for col in go_emotions.columns:
    go_emotions[col] = go_emotions[col].apply(clean_lists)

go_emotions.dropna(inplace=True)
go_emotions.head()

                                                text emotions_merged
0                                    That game hurt.             sad
3                                 Man I love reddit.             joy
7  That's crazy; I went to a super [RELIGION] hig...             joy
8                                that's adorable asf             joy
9  "Sponge Blurb Pubs Quaw Haha GURR ha AAa!" fin...             joy

## Data Save
>We are finally saving the dataset treated to the subfolder preprocessed of data.

In [11]:
go_emotions.to_csv("../data/preprocessed/go-emotions.csv", index=False)